# Generated by Django 2.1.5 on 2019-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='language',
            field=models.ManyToManyField(related_name='_language', to='API.Languages'),
        ),
    ]
